service: exo-flask

provider:
  name: aws
  runtime: python3.12
  region: us-east-1  # Update to your preferred region

functions:
  app:
    handler: exo_service.app
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
